In [1]:
#Importing the necessary packages
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = sns.load_dataset('iris')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['species'] = encoder.fit_transform(df['species'])

In [4]:
df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [5]:
df['species'].value_counts()

species
0    50
1    50
2    50
Name: count, dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 5.4 KB


In [7]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width     species
count    150.000000   150.000000    150.000000   150.000000  150.000000
mean       5.843333     3.057333      3.758000     1.199333    1.000000
std        0.828066     0.435866      1.765298     0.762238    0.819232
min        4.300000     2.000000      1.000000     0.100000    0.000000
25%        5.100000     2.800000      1.600000     0.300000    0.000000
50%        5.800000     3.000000      4.350000     1.300000    1.000000
75%        6.400000     3.300000      5.100000     1.800000    2.000000
max        7.900000     4.400000      6.900000     2.500000    2.000000

In [8]:
# split the data into indep and dep variable

x = df.iloc[:,0:-1]
y = df[['species']]

In [9]:
x.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [10]:
y.head()

species
0        0
1        0
2        0
3        0
4        0

In [11]:
# split the data into train and test
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=1)

In [13]:
#Model building
from sklearn.linear_model import LogisticRegression
logit_ovr = LogisticRegression(multi_class='ovr')
logit_ovr.fit(x_train, y_train)

LogisticRegression(multi_class='ovr')

LogisticRegression(multi_class='ovr')

In [14]:
# predict
y_pred_train = logit_ovr.predict(x_train)
y_pred_test = logit_ovr.predict(x_test)

In [16]:
#Evaluation

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

print("Training Accuracy Score :", accuracy_score(y_train, y_pred_train))
print("****************"*10)
print("Test Accuracy Score :", accuracy_score(y_test, y_pred_test))

Training Accuracy Score : 0.9553571428571429
****************************************************************************************************************************************************************
Test Accuracy Score : 0.8947368421052632


In [17]:
print( classification_report(y_train, y_pred_train))
print("****************"*10)
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       0.97      0.88      0.92        34
           2       0.91      0.98      0.94        41

    accuracy                           0.96       112
   macro avg       0.96      0.95      0.95       112
weighted avg       0.96      0.96      0.96       112

****************************************************************************************************************************************************************
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.75      0.86        16
           2       0.69      1.00      0.82         9

    accuracy                           0.89        38
   macro avg       0.90      0.92      0.89        38
weighted avg       0.93      0.89      0.90        38



In [18]:
print( confusion_matrix(y_train, y_pred_train))
print("****************"*10)
print(confusion_matrix(y_test, y_pred_test))

[[37  0  0]
 [ 0 30  4]
 [ 0  1 40]]
****************************************************************************************************************************************************************
[[13  0  0]
 [ 0 12  4]
 [ 0  0  9]]


In [20]:
#Building a logisticRegressionModel with multinomial

logit_multi = LogisticRegression(multi_class='multinomial')
logit_multi.fit(x_train, y_train)

LogisticRegression(multi_class='multinomial')

In [21]:
y_pred_train_m = logit_multi.predict(x_train)
y_pred_test_m = logit_multi.predict(x_test)

In [22]:
print("Training Accuracy Score :", accuracy_score(y_train, y_pred_train_m))
print("****************"*10)
print("Test Accuracy Score :", accuracy_score(y_test, y_pred_test_m))

Training Accuracy Score : 0.9821428571428571
****************************************************************************************************************************************************************
Test Accuracy Score : 0.9736842105263158


In [23]:
print( classification_report(y_train, y_pred_train_m))
print("****************"*10)
print(classification_report(y_test, y_pred_test_m))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       1.00      0.94      0.97        34
           2       0.95      1.00      0.98        41

    accuracy                           0.98       112
   macro avg       0.98      0.98      0.98       112
weighted avg       0.98      0.98      0.98       112

****************************************************************************************************************************************************************
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.94      0.97        16
           2       0.90      1.00      0.95         9

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38



In [24]:
confusion_matrix(y_train, y_pred_train_m)
print("****************"*10)
confusion_matrix(y_test, y_pred_test_m)

****************************************************************************************************************************************************************


array([[13,  0,  0],
       [ 0, 15,  1],
       [ 0,  0,  9]], dtype=int64)

In [28]:
sns.heatmap(advertising.corr(), cmap="Cyan", annot = True)
plt.show()

NameError: name 'advertising' is not defined